language: node_js
node_js:
  - '10'

before_script:
  - yarn

stages:
  - lint
  - publish

jobs:
  include:
    - stage: lint
      script: yarn lint

    - stage: publish
      branches:
        only:
          - dev
      script: bash scripts/publish.sh
